# Generated by Django 3.2.19 on 2023-05-25 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('nombre', models.CharField(max_length=45, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('patente', models.TextField(primary_key=True, serialize=False)),
                ('nombre_modelo', models.CharField(max_length=45)),
                ('marca', models.CharField(max_length=45)),
                ('año', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webRayo.categoria')),
            ],
        ),
    ]
