# Generated by Django 3.2.19 on 2023-05-26 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webRayo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='foto',
            field=models.ImageField(default=2, upload_to=''),
            preserve_default=False,
        ),
    ]
