# Generated by Django 3.2.19 on 2023-05-26 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webRayo', '0002_vehiculo_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='foto',
            field=models.ImageField(upload_to='fotos'),
        ),
    ]
